# Generated by Django 4.2.26 on 2025-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.CharField(max_length=30),
        ),
    ]
